//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_Sensor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdSensorTypes { get; set; }
        public Nullable<int> IdMeasurementUnits { get; set; }
    
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual SensorType SensorType { get; set; }
    }
}
